# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlActor
version:      0.02
version_from: lib/PerlActor.pm
installdirs:  site
requires:
    Benchmark:                     1
    File::Find:                    1
    Test::Unit:                    0.24

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
